### PR TITLE
allow sourcemap option

### PR DESCRIPTION
**Pull request by chris-schra**
Allowing sourcemap makes it MUCH easier.. just an idea and a quick win :D

### CODE REVIEW

**Comment by chris-schra** [comment]
ah, and another small thing in package.json:
`"packageManager": "pnpm@pnpm@9.11.0",`
didn't work for me, so I changed it to
`"packageManager": "pnpm@9.11.0",`

**Comment by antitoxic** [comment]
> Allowing sourcemap

Awesome! Also glad you are finding the package useful. Are you ok adding an inline comment about why we have this new option despite not related to resolution?

> "packageManager": "pnpm@pnpm@9.11.0",

✋ my bad. Do you want to commit it?

**Comment by antitoxic** [comment]
Hey @chris-schra just checking if you have the time to update the PR? Let me know if you don't.

**Comment by antitoxic** [comment]
This was incorporate in: https://github.com/antitoxic/import-single-ts/commit/ff823aa323b62d347d239bdb00d6e2953051add3#diff-50b78e694e42b38c0b5ef92c09077d34c85671dfbb8fc6b51fac898007b175a7R195

Available in v1.2.0.

**Pull request closed without merging**
